---
title: "my-vignette"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{my-vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(CoralGenetics)
```


```{r}

# Need these packages
library(magrittr)
# library(dplyr) # data manipulation
# library(tidyr) # reshaping data (pivoting)
# library(Matrix) # for the graph/network analysis part
# library(igraph) # for the graph/network analysis part
# library(stringi) # for removing whitespace
# library(stringr) #### string matching
# library(matrixStats) # for kinship calculations

## Determine folder paths - just set the working directory to the right place and this will work fine. 
# folderPaths <- list.dirs(path = paste0(getwd()), full.names = TRUE, recursive = F)

#### Specify locations of data and results folders: changed this is bit so we're not hard-wiring folderPaths[1] and folderPaths[2] but instead matching "Data" and "Results" strings. This is case sensitive so i's got to be Data and Results. 
# dataLocation <- folderPaths[which(str_detect(folderPaths, "Data")==TRUE)]
# resultsLocation <- folderPaths[which(str_detect(folderPaths, "Results")==TRUE)]

## Create an empty list for storing genet assignment results
# genetAssignment <- list()

## Create a list of file names to be processed for genet assignment/kinshup etc. 
# fileList <- as.list(list.files(path = dataLocation, pattern = "\\.csv$"))
#raw <- read.csv(paste0(dataLocation,"/",rawDataName), stringsAsFactors = F, colClasses = c("character"), na.strings = "")

#------------------------------------------#

## Read in the allele data (rows = individuals and columns = loci)
initdata <- readGeneticData("C:/Users/Kristen.Sauby/Documents/Projects/CoralGenetics/inst/testdata.csv")
# add some fake data so that a genet has two clones
newrecord <- initdata[1,]
newrecord$Coral_ID <- "10_EFAS_007"

initdata %<>% rbind(newrecord)

initdata_bad <- initdata %>% dplyr::select(-Coral_ID)
#### Make sure that the data we're using are ONLY either the Coral_ID OR one of the character strings included in OnlyDataAllowed. If there are no such columns then nothing happens. There's probably a more elegant way to do this but it works fine. 
wideclean <- convertBasePairstoCodes(initdata)

translatedAlleles <- wideclean #changes the name for exporting purposes only, to make sure that the null thing down below doesn't modify the table that gets exported
# wideclean[wideclean=="?"] <- NA # Changes all the "?" to nulls for the sake of the genet calculations.# taken care of in readGeneticData

## Not completely necessary but here renaming for use in functions, below.
wideclean[wideclean=="?"] <- NA
coralAlleleData <- wideclean

AlleleMatchResults <- determineAllAlleleMatches(coralAlleleData)

finalresults <- groupByGenets(AlleleMatchResults)
```

